### ISSUE TITLE
No embedded binary found for shellcheck with Windows

### ISSUE THREAD

**Issue by aelliott-push** [marco-nicolini/shellcheck-maven-plugin#4]
plugin fails to find embedded binary when run on Windows machines, works fine on Linux.

build fails after this log:

[INFO] os arch: [Windows_10-amd64]
[DEBUG] Detected arch is [Windows_x86]
[DEBUG] Path [\target\shellcheck-plugin\shellcheck.exe] was created? [true]
[DEBUG] Will try to use binary [/shellcheck-bin/Windows_x86/shellcheck-v0.8.0.exe]

Does the binary in the embedded jar have a different name/version?

I'm using plugin version 0.4.0

**Comment by giraciopide** [comment]
I'll look at it. As I don't have a windows machine to actually test it might take a while if it's not obvious by looking at the code.

**Comment by giraciopide** [comment]
The name which is assumed for the embedded binary for windows is wrong. 
It was changed in the released windows binary for shellcheck.
Shellcheck v.0.7.1 had shellcheck-v.0.7.1.exe in the release zip, while from 0.7.2 onward shellcheck.exe is there.

Admittedly there is no "smartness" in figuring out what is the binary: the expected name is hardcoded, but I missed this it because I'm not building it on Windows.

**Comment by giraciopide** [comment]
I released 0.4.1 that should fix this.
It will take some time (minutes to hours) to be synced to maven central, and will take more to actually appear in searches.

Please try it out and report back if it's fixed.

There is still no smartness to adapt to potential future changes in the different release layout of shellcheck, but there is now a test that will break if the hardcoded paths do not match what's being included in the jar, so all in all it should be spotted while I update the embedded binaries (regardless of the arch where the plugin is being built).

**Comment by giraciopide** [comment]
I also setup some CI action to build on linux/win/macos, so this kind of problem will definitely be spotted from now on (as there were already integration tests using the embedded binaries that would have failed on windows).

**Comment by aelliott-push** [comment]
Thanks for the quick fix. Version 0.4.1 works on my machine.
